- name: Directory is present
  file:
    path=/data/sample-spring-cloud-svc-ci/db
    state=directory
  tags: [sample-spring-cloud-svc-ci]

- name: Latest container is pulled
  shell: sudo docker pull 192.168.50.91:5000/sample-spring-cloud-svc-ci
  tags: [sample-spring-cloud-svc-ci]

- name: Container is absent
  docker:
    image=192.168.50.91:5000/sample-spring-cloud-svc-ci
    name=sample-spring-cloud-svc-ci
    state=absent
  tags: [sample-spring-cloud-svc-ci]

- name: Container is running
  docker:
    name=sample-spring-cloud-svc-ci
    image=192.168.50.91:5000/sample-spring-cloud-svc-ci
    ports=9002:8080
    volumes=/data/sample-spring-cloud-svc-ci/db:/data/db
    state=running
  tags: [sample-spring-cloud-svc-ci]
